name: test

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up Node environment
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run check target
        run: make check

  frontend-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['20', '22']
      fail-fast: false
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up Node environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run test target
        working-directory: frontend
        run: make test

  frontend-coverage:
    runs-on: ubuntu-latest
    needs: frontend-test

    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up Node environment
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run coverage target
        working-directory: frontend
        run: make coverage

      - name: Upload HTML report if check failed.
        uses: actions/upload-artifact@v4
        with:
          name: frontend-report
          path: coverage
        if: ${{ failure() }}

